PetNetCore/Controllers/AnimalController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PetNetCore.Entity;
using PetNetCore.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace PetNetCore.Controllers
{
    [Authorize]
    public class AnimalController : Controller
    {
        PetNETv2Context _context;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IWebHostEnvironment _env;
        public AnimalController(PetNETv2Context context, IHttpContextAccessor httpContextAccessor, IWebHostEnvironment env)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
            _env = env;
        }
        // GET: AnimalController
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult List()
        {
            ViewBag.animals = _context.Animal.Include(a => a.User).Include(a => a.Breed).Select(s => new AnimalDto
            {
                Name = s.Name,
                Age = s.Age,
                Description = s.Description,
                Photo = s.Photo,
                BreedName = s.Breed.BreedName,
                Username = s.User.Username,
            }).ToList();
            return View();
        }
        [HttpPost]
        public ActionResult ListByUserId()
        {
            string userId = User.Claims.Where(c => c.Type == "UserId").FirstOrDefault().Value;
            ViewBag.animals = _context.Animal.Where(m=> m.UserId == Int32.Parse(userId)).Select(s => new AnimalDto
            {
                Name = s.Name,
                Age = s.Age,
                Description = s.Description,
                Photo = s.Photo,
                BreedName = s.Breed.BreedName,
                Username = s.User.Username,
            }).ToList();
            return View("List");
        }
        public ActionResult Create()
        {
            return View();
        }
        //POST: AnimalController/Create
       [HttpPost]
        public ActionResult Create(AnimalDto animalModel, IFormFile photo)
        {
            try
            {
                string uniqueFileName = null;
                if (photo != null)
                {
                    string uploadsFolder = Path.Combine(_env.WebRootPath, "images");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + photo.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        photo.CopyTo(fileStream);
                    }
                }
                string userId = User.Claims.Where(c=>c.Type == "UserId").FirstOrDefault().Value;
                var animal = new Animal
                {
                    Name = animalModel.Name,
                    Age = animalModel.Age,
                    Description = animalModel.Description,
                    Photo = uniqueFileName,
                    BreedId = animalModel.BreedId,
                    UserId = Int32.Parse(userId),
                };
                _context.Animal.Add(animal);
                _context.SaveChanges();
                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

    }
}

PetNetCore/Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PetNetCore.Entity;
using PetNetCore.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace PetNetCore.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        PetNETv2Context _context;
        IWebHostEnvironment _env;
        public UserController(PetNETv2Context context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        // GET: UserController
        public IActionResult Index()
        {
            var blogposts = _context.BlogPost.Include(a => a.User).Select(s => new BlogPostDto.List
            {
                BlogTitle = s.BlogTitle,
                BlogContent = s.BlogContent,
                Photo = s.Photo,
                Username = s.User.Username,
            }).ToList();
            return View(blogposts);
        }
        public IActionResult CreateBlogPost(BlogPostDto.List model, IFormFile photo)
        {

            try
            {
                string uniqueFileName = null;
                if (photo != null)
                {
                    string uploadsFolder = Path.Combine(_env.WebRootPath, "images");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + photo.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        photo.CopyTo(fileStream);
                    }
                }
                string userId = User.Claims.Where(c => c.Type == "UserId").FirstOrDefault().Value;
                var blogPost = new BlogPost
                {
                    BlogTitle = model.BlogTitle,
                    BlogContent = model.BlogContent,
                    Photo = uniqueFileName,
                    UserId = Int32.Parse(userId),
                };
                _context.BlogPost.Add(blogPost);
                _context.SaveChanges();
                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }

        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        public IActionResult ListBlogPosts()
        {
            ViewBag.blogposts = _context.BlogPost.Include(m => m.User).Select(s => new BlogPostDto.List
            {
                BlogTitle = s.BlogTitle,
                BlogContent = s.BlogContent,
                Photo = s.Photo,
                Username = s.User.Username,
            }).ToList();
            return View();
        }
        [HttpPost]
        public IActionResult ListBlogPostsByUserId()
        {
            string userId = User.Claims.Where(c => c.Type == "UserId").FirstOrDefault().Value;
            ViewBag.blogposts = _context.BlogPost.Include(m => m.User).Where(m => m.UserId == Int32.Parse(userId)).Select(s => new BlogPostDto.List
            {
                BlogTitle = s.BlogTitle,
                BlogContent = s.BlogContent,
                Photo = s.Photo,
                Username = s.User.Username,
            }).ToList();
            return View("ListBlogPosts");
        }
        public IActionResult Account(int id)
        {
            var user = _context.User.Include(u => u.Role).Where(u => u.Id == id).Select(s => new UserDto.Account
            {
                Id = s.Id,
                Username = s.Username,
                FirstName = s.FirstName,
                LastName = s.LastName,
                BirthDate = s.BirthDate,
                City = s.City,
                Phone = s.Phone,
                Role = s.Role.RoleName,
                Photo = s.Photo,
            }).FirstOrDefault();
            return View(user);
        }

        public IActionResult AddBlogPost()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddBlogPost(BlogPostDto.List model, IFormFile photo)
        {
            try
            {
                string uniqueFileName = null;
                if (photo != null)
                {
                    string uploadsFolder = Path.Combine(_env.WebRootPath, "images");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + photo.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        photo.CopyTo(fileStream);
                    }
                }
                string userId = User.Claims.Where(c => c.Type == "UserId").FirstOrDefault().Value;
                var blogPost = new BlogPost
                {
                    BlogTitle = model.BlogTitle,
                    BlogContent = model.BlogContent,
                    Photo = uniqueFileName,
                    UserId = Int32.Parse(userId),
                };
                _context.BlogPost.Add(blogPost);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }

        }
        [HttpPost]
        public async Task<IActionResult> UpdateProfile(UserDto.Register model, IFormFile photo)
        {
            string uniqueFileName = null;
            if (photo != null)
            {
                string uploadsFolder = Path.Combine(_env.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    photo.CopyTo(fileStream);
                }
            }
            string userId = User.Claims.Where(c => c.Type == "UserId").FirstOrDefault().Value;
            var user = _context.User.Where(m => m.Id == Int32.Parse(userId)).FirstOrDefault();

            user.Username = model.Username;
            user.Password = model.Password;
            user.FirstName = model.FirstName;
            user.LastName = model.LastName;
            user.BirthDate = (model.BirthDate != null) ? model.BirthDate : user.BirthDate;
            user.City = model.City;
            user.Photo = (photo != null) ? uniqueFileName : user.Photo;
            user.Phone = (model.Phone != null) ? model.Phone : user.Phone;

            _context.User.Update(user);
            _context.SaveChanges();
            return RedirectToAction("Account", new { id = user.Id });
        }
        public IActionResult UpdateProfile()
        {
            string userId = User.Claims.Where(c => c.Type == "UserId").FirstOrDefault().Value;
            var user = _context.User.Where(m => m.Id == Int32.Parse(userId)).Select(s => new UserDto.Register
            {
                Username = s.Username,
                FirstName = s.FirstName,
                LastName = s.LastName,
                BirthDate = s.BirthDate,
                Photo = s.Photo,
                City = s.City,
                Phone = s.Phone,
                Password = s.Password,
            }).FirstOrDefault();
            return View(user);
        }

    }
}

PetNetCore/Views/Animal/Create.cshtml
@model PetNetCore.Models.AnimalDto

@{
    ViewData["Title"] = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Create", "Animal", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <div class="form-horizontal">
        <h4>Add Animal</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, "Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @required = "" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, "Age", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control", @required = "" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" }, @required = "" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.BreedId, "Breed", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BreedId, new { htmlAttributes = new { @class = "form-control" }, @required = "" })
                @Html.ValidationMessageFor(model => model.BreedId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Photo, "Photo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="photo" id="photo" accept=".jpeg,.JPEG,.Jpeg,.gif,.png" class="form-control" />
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=Add class="btn btn-default" />
            </div>
        </div>
    </div>

}
<p>

    @Html.ActionLink("Back", "Index","User")
</p>

PetNetCore/Views/Animal/List.cshtml
@using PetNetCore.Models;
@{
    Layout = "~/Views/Shared/LayoutPage.cshtml";
}

<h1>
    Animals for Adoption
</h1>
@foreach (AnimalDto animal in (List<AnimalDto>)ViewBag.animals)
{
    <div class="col-lg-12 col-sm-3 portfolio-item">
        <div class="card h-100">
            @if (animal.Photo != null)
            {<a href="#"><img class="card-img-top" src="~/images/@animal.Photo"></a>}
            <div class="card-body">
                <h3>
                    <td>
                        @Html.DisplayFor(modelItem => animal.Name)
                    </td>
                </h3>
                <hr />
                <p> <b>Name : </b>@Html.DisplayFor(modelItem => animal.Age)</p>
                <hr />
                <p> <b>Description :  </b> @Html.DisplayFor(modelItem => animal.Description)</p>
                <hr />
                <p> <b>Breed : </b>@Html.DisplayFor(modelItem => animal.BreedName)</p>
                <hr />
                <p> <b>Owner :  </b> @Html.DisplayFor(modelItem => animal.Username)</p>


            </div>
        </div>
    </div>
} 
<p>

    @Html.ActionLink("Back", "Account","User")
</p>